### ISSUE TITLE
Use sane version tagging

### ISSUE THREAD

**Issue by RealRancor** [kas70/Dicer#3]
Hi,

the Auto Update of the current version 1.1 on F-Droid is failing because the previous versions where tagget as v1.0 and v1.01 where the current is only tagged as 1.1.

Are you planning to use the tagging format to tags without the "v" for all newer versions? I can then update the Auto Update mode according to used format.

**Comment by kas70** [comment]
hi,
thanks for the note. i think it should be ok now (new release is now tagged with v1.1).

**Comment by RealRancor** [comment]
Thanks for the update. The app should build correctly at the next time.
